name: Auto Assign & Scalable Triage
# This workflow is optimized for an open-source monorepo, providing intelligent
# triage labels for new issues and rotating assignments for pull requests.
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  triage_and_default_assign:
    # This job runs for ALL new issues and PRs. It ensures:
    # 1. A default core member is assigned for initial review/triage (lvllc904).
    # 2. Issues are immediately labeled for filtering (e.g., 'status:needs-triage').
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      pull-requests: write
      
    steps:
      # 1. Assigns a default core assignee for all new issues/PRs
      - name: 'Assign Default Core Triage'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Set a default core assignee for all incoming work. 
          assignees: lvllc904, core-triage-team # Added team for scalability
          numOfAssignee: 1
          
      # 2. Add an initial triage label for filtering/dashboard view
      - name: 'Add Triage Label'
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event_name == 'issues' || github.event_name == 'pull_request'
        with:
          labels: status:needs-triage, effort:unestimated
          github_token: ${{ secrets.GITHUB_TOKEN }}

  assign_specialist_reviewer:
    # This job runs only if changes are detected in critical application paths (Pull Requests only).
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: triage_and_default_assign # Ensures default assignment is complete before specialist assignment
    
    permissions:
      pull-requests: write
      
    steps:
      # 1. Checkout repository to enable path filtering
      - uses: actions/checkout@v4
      
      # 2. Filter paths to identify which component was changed
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/nextjs-app/**'
              - 'packages/core-models/**'
            backend_ai:
              - 'services/lesson-planner-factory/**'
              - 'services/talos-agent/**'
            infrastructure:
              - '.github/workflows/**'
              - 'dev.nix'
              
      # 3. Conditional Assignment for Frontend (UI/Client-side logic)
      - name: 'Assign Frontend Reviewer'
        if: steps.filter.outputs.frontend == 'true'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Assign a pool of users for review rotation (use comma-separated list)
          assignees: frontend-lead, reviewer-a, reviewer-b
          numOfAssignee: 1

      # 4. Conditional Assignment for Backend AI/RAG (Python services)
      - name: 'Assign AI/Backend Reviewer'
        if: steps.filter.outputs.backend_ai == 'true'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Assign pool of AI/Python specialists
          assignees: backend-lead, python-specialist, ml-engineer
          numOfAssignee: 1
